# Generated by Django 4.0.4 on 2022-06-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kino_name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=1000)),
                ('genre', models.CharField(max_length=80)),
                ('country', models.CharField(max_length=30)),
                ('director', models.CharField(max_length=30)),
            ],
        ),
    ]
