# Generated by Django 3.2.13 on 2022-06-06 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_price_delete_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('text', models.TextField(verbose_name='текст комментария')),
                ('kino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comments.kino')),
            ],
        ),
    ]
