# Generated by Django 4.0.5 on 2022-06-07 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_add'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add',
            old_name='text',
            new_name='name',
        ),
    ]
