# Generated by Django 4.0.5 on 2022-06-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0008_rename_text_add_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='film',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='add',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
